name: CD

on:
  push:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: extractions/setup-just@v4
      - name: Preview version bump
        run: just bump --dry-run

  bump:
    runs-on: ubuntu-latest
    needs: preview
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: extractions/setup-just@v4
      - run: just --yes release
